#!/usr/bin/env bun
/**
 * sync-from-openapi — half-automated maintenance of `references/api.md`.
 *
 * Fetches the live BibiGPT OpenAPI spec (or a local file via $BIBI_OPENAPI),
 * groups paths by tag, and emits a Markdown reference. Designed to handle
 * the *churn-prone* parts of api.md (endpoint list + params + curl) so the
 * human-curated parts (auth, error handling, agent workflows) stay editable.
 *
 * Usage:
 *   bun packages/bibigpt-skill/scripts/sync-from-openapi.ts            # preview to stdout
 *   bun packages/bibigpt-skill/scripts/sync-from-openapi.ts --write    # overwrite endpoints.md
 *   BIBI_OPENAPI=./fixture.json bun ... sync-from-openapi.ts           # use local file
 *
 * Output is written to `skills/bibi/references/endpoints.md` (separate
 * from the human-curated `references/api.md`) so the script can refresh
 * without touching workflows + auth docs. Phase 4.2.
 */

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const DEFAULT_URL = 'https://bibigpt.co/api/openapi.json'
const ENDPOINTS_OUT = resolve(__dirname, '..', 'skills', 'bibi', 'references', 'endpoints.md')

type OpenApiOperation = {
  summary?: string
  description?: string
  tags?: string[]
  parameters?: Array<{
    name: string
    in: string
    required?: boolean
    description?: string
    schema?: { type?: string }
  }>
  requestBody?: {
    content?: Record<string, { schema?: unknown }>
  }
  responses?: Record<string, unknown>
}
type OpenApiSpec = {
  info?: { title?: string; version?: string }
  paths?: Record<string, Record<string, OpenApiOperation>>
}

async function loadSpec(): Promise<OpenApiSpec> {
  const localPath = process.env.BIBI_OPENAPI
  if (localPath) {
    const file = Bun.file(localPath)
    if (!(await file.exists())) {
      throw new Error(`BIBI_OPENAPI=${localPath} does not exist`)
    }
    return (await file.json()) as OpenApiSpec
  }
  const resp = await fetch(DEFAULT_URL)
  if (!resp.ok) {
    throw new Error(`GET ${DEFAULT_URL} → HTTP ${resp.status}`)
  }
  return (await resp.json()) as OpenApiSpec
}

function curlExample(method: string, path: string, op: OpenApiOperation): string {
  const upper = method.toUpperCase()
  const url = `https://api.bibigpt.co/api${path}`
  if (upper === 'GET' || upper === 'DELETE') {
    const params = (op.parameters ?? []).filter(p => p.in === 'query')
    const qs = params.map(p => `${p.name}=<${p.name}>`).join('&')
    const fullUrl = qs ? `"${url}?${qs}"` : `"${url}"`
    const flags = upper === 'DELETE' ? `-X DELETE ` : ''
    return `curl -s ${flags}-H "Authorization: Bearer $BIBI_API_TOKEN" \\\n  ${fullUrl}`
  }
  // POST/PUT/PATCH — assume JSON body shaped from request body
  const bodyDesc = op.requestBody ? '{ ... }' : '{}'
  return [
    `curl -s -X ${upper} -H "Authorization: Bearer $BIBI_API_TOKEN" \\`,
    `  -H "Content-Type: application/json" \\`,
    `  -d '${bodyDesc}' \\`,
    `  "${url}"`,
  ].join('\n')
}

function renderEndpoint(method: string, path: string, op: OpenApiOperation): string {
  const lines: string[] = []
  lines.push(`### \`${method.toUpperCase()} ${path}\``)
  lines.push('')
  if (op.summary) {
    lines.push(`> ${op.summary}`)
    lines.push('')
  }
  if (op.description && op.description !== op.summary) {
    lines.push(op.description)
    lines.push('')
  }
  const queryParams = (op.parameters ?? []).filter(p => p.in === 'query')
  if (queryParams.length > 0) {
    lines.push('| Param | Type | Required | Description |')
    lines.push('|---|---|---|---|')
    for (const p of queryParams) {
      lines.push(
        `| \`${p.name}\` | ${p.schema?.type ?? '—'} | ${p.required ? 'yes' : 'no'} | ${p.description ?? ''} |`,
      )
    }
    lines.push('')
  }
  lines.push('```bash')
  lines.push(curlExample(method, path, op))
  lines.push('```')
  lines.push('')
  return lines.join('\n')
}

function renderMarkdown(spec: OpenApiSpec): string {
  const out: string[] = []
  out.push(`# OpenAPI Endpoints (auto-generated)`)
  out.push('')
  out.push(`> **Do not edit this file by hand.** Regenerate via:`)
  out.push('> ```bash')
  out.push('> bun packages/bibigpt-skill/scripts/sync-from-openapi.ts --write')
  out.push('> ```')
  out.push('>')
  out.push(`> Source: ${process.env.BIBI_OPENAPI ?? DEFAULT_URL}`)
  out.push('')

  const info = spec.info ?? {}
  if (info.title) {
    out.push(`Spec: **${info.title}**${info.version ? ` (v${info.version})` : ''}`)
    out.push('')
  }

  // Group endpoints by primary tag (first tag if multiple); fall back to "untagged".
  const byTag = new Map<string, Array<{ method: string; path: string; op: OpenApiOperation }>>()
  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const [method, op] of Object.entries(methods)) {
      const tag = op.tags?.[0] ?? 'untagged'
      if (!byTag.has(tag)) byTag.set(tag, [])
      byTag.get(tag)!.push({ method, path, op })
    }
  }

  // Stable order: tags alphabetically, endpoints by path.
  const sortedTags = [...byTag.keys()].sort()
  for (const tag of sortedTags) {
    const entries = byTag.get(tag)!.sort((a, b) => (a.path < b.path ? -1 : 1))
    out.push(`## ${tag}`)
    out.push('')
    for (const { method, path, op } of entries) {
      out.push(renderEndpoint(method, path, op))
    }
  }

  return out.join('\n')
}

async function main() {
  const args = process.argv.slice(2)
  const writeMode = args.includes('--write')

  const spec = await loadSpec()
  const md = renderMarkdown(spec)

  if (!writeMode) {
    console.log(md)
    return
  }

  writeFileSync(ENDPOINTS_OUT, md, 'utf8')
  console.error(`✓ wrote ${ENDPOINTS_OUT}`)
  console.error(`  ${Object.values(spec.paths ?? {}).reduce((acc, m) => acc + Object.keys(m).length, 0)} endpoints, ${md.split('\n').length} lines`)
}

main().catch(err => {
  console.error(`✗ sync-from-openapi failed: ${err instanceof Error ? err.message : err}`)
  process.exit(1)
})
